'use client';

/**
 * B.1.2 / B.1.3 — `/classroom-demo` route.
 *
 * Mirrors the B.1 `/classroom-front-snapshot-fixture` route in shape
 * but flips the data source: every page load generates a NEW random
 * classroom (5–8 students, random lesson, random teacher speech,
 * random desk bubbles, random chalk strokes, random hand-raise queue,
 * random chat history, random homework problem, random mistake list,
 * random pomodoro timer).
 *
 * Two facts to keep in mind:
 *
 *   1. The fixture route is FROZEN — it stays hand-picked so the
 *      Playwright snapshot baselines stay reproducible. This route is
 *      the opposite: every refresh is fresh.
 *   2. The store-driven `classroom` slice keeps its B.1 shape; the
 *      per-desk dynamic data (bubble content / hand-raise flag /
 *      display name) is forwarded into `<ClassroomFront />` via props
 *      so we don't have to extend `ClassroomState`.
 *   3. B.1.3 — the `<ClassroomFront />` is now nested inside a full
 *      3-pane `<DemoShell />` (top header + chat history + main
 *      split + bottom input bar). All extra payload (chat history,
 *      homework problem, mistake list, pomodoro, mode tabs, chat
 *      badge) is also generated by `generateDemoClassroomState()` and
 *      passed in via `<DemoShell />` props.
 */

import { useEffect, useMemo, useState } from 'react';
import { DemoShell } from '@/components/classroom-shell/demo-shell';
import { isClassroomFrontEnabled } from '@/lib/config/feature-flags';
import { useStageStore } from '@/lib/store/stage';
import {
  generateDemoClassroomState,
} from '@/lib/classroom/demo-data-generator';

export default function ClassroomDemoPage() {
  const enabled = isClassroomFrontEnabled();

  // Bump a render key on every mount to guarantee a fresh seed even
  // when StrictMode double-invokes effects.
  const [renderKey, setRenderKey] = useState(0);

  // Generate fresh data on every (re)mount. Keeping this in `useMemo`
  // (not `useEffect`) means `displayNameByAgentId` is available to
  // `<ClassroomFront />` on the same render that mounts the page —
  // before, the page rendered once with `displayNameByAgentId ===
  // undefined` and only caught up after `setDynamic(...)`, which
  // surfaced as desks falling back to the `agent_id` string
  // (e.g. "agent-0-👵") instead of the Chinese name (e.g. "小红").
  const generation = useMemo(() => {
    const gen = generateDemoClassroomState();
    return {
      classroom: gen.classroom,
      dynamic: gen.dynamic,
      displayNameByAgentId: gen.displayNameByAgentId,
      seed: gen.seed,
      chatHistory: gen.chatHistory,
      courseware: gen.courseware,
      homework: gen.homework,
      header: gen.header,
    };
  }, [renderKey]);
  const {
    classroom,
    dynamic,
    displayNameByAgentId,
    seed,
    chatHistory,
    courseware,
    homework,
    header,
  } = generation;

  useEffect(() => {
    if (!enabled) return;

    // Seed the store. We intentionally bypass the persistence-marking
    // path here because this is a transient visual demo — we don't
    // want every refresh to schedule an IndexedDB write. The same
    // pattern is used by the snapshot fixture route.
    useStageStore.setState({
      classroom,
    });
  }, [classroom, enabled]);

  // Re-generate on demand (manual refresh button — now lives inside
  // <TopHeader /> rather than as a floating absolute overlay so the
  // demo route is fully mockup-faithful).
  const handleRefresh = () => {
    setRenderKey((k) => k + 1);
  };

  if (!enabled) {
    return (
      <div
        data-testid="classroom-demo"
        data-front-disabled="true"
        style={{
          width: 1280,
          minHeight: 800,
          padding: 24,
          color: '#999',
          fontFamily: 'system-ui, sans-serif',
        }}
      >
        front-view flag is OFF — start dev server with NEXT_PUBLIC_CLASSROOM_FRONT_ENABLED=true.
      </div>
    );
  }

  return (
    <div
      data-testid="classroom-demo"
      data-demo-seed={seed}
      data-current-slide={courseware.currentSlide}
      style={{
        position: 'relative',
        width: 1280,
        height: 800,
        background: '#f6f5fb',
        fontFamily: "'Inter', system-ui, sans-serif",
      }}
    >
      <DemoShell
        teacherBubbleContent={dynamic.teacherBubble}
        deskBubbleContents={Object.fromEntries(
          Object.entries(dynamic.deskByAgentId).map(([agentId, v]) => [
            agentId,
            v.bubbleContent ?? '',
          ]),
        )}
        deskDisplayNames={displayNameByAgentId}
        deskHandRaised={Object.fromEntries(
          Object.entries(dynamic.deskByAgentId).map(([agentId, v]) => [
            agentId,
            v.handRaised,
          ]),
        )}
        activeCallOnAgentId={dynamic.activeCallOnAgentId}
        chatHistory={chatHistory}
        problem={homework.problem}
        mistakes={homework.mistakes}
        modeTabs={header.modeTabs}
        pomodoroSeconds={header.pomodoroSeconds}
        teacherName={header.teacherName}
        chatBadgeCount={header.chatBadgeCount}
        onRefresh={handleRefresh}
      />
    </div>
  );
}
